FROM python:3.11-slim

# Environment 
ENV PYTHONUNBUFFERED=1

# Working directory
WORKDIR /app

# Instalamos dependencias de Python 
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar código
COPY main.py .

# Copiar carpeta de modelos
COPY models ./models

# Exponemos el puerto 80
EXPOSE 80

# Run API with uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
